---
galaxy_info:
  author: Daniel Perez Alvarez
  description: Ansible profile role for Perl developers
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system

dependencies:
  - profile-dev
