---
- name: Install pyenv
  ansible.builtin.git: repo=https://github.com/pyenv/pyenv.git dest=~/.pyenv

- name: Install {{ pyenv.python_version }}
  shell: ~/.pyenv/bin/pyenv install --skip-existing {{ pyenv.python_version }}
  register: pyenv_install_result
  changed_when: "'' == pyenv_install_result.stdout"

- name: Check if {{ pyenv.python_version }} is the default Python version
  shell: ~/.pyenv/bin/pyenv global | grep -e '{{ pyenv.python_version }}'
  register: pyenv_check_default
  changed_when: no
  ignore_errors: yes

- name: Set default Python version to {{ pyenv.python_version }}
  shell: ~/.pyenv/bin/pyenv global {{ pyenv.python_version }}
  when: pyenv_check_default is failed
